import { TableDataSet } from './types';

export const mockTableDataSets: TableDataSet[] = [
  {
    id: 1,
    name: 'Project profit',
    header: [
      { id: 'project_name', type: 'string', caption: 'Project name' },
      { id: 'total_by_project', type: 'float', caption: 'Total by project' },
      {
        id: 'project_type',
        type: 'string',
        caption: 'Project type',
        align: 'center',
      },
      { id: 'jan', type: 'float', caption: 'Jan' },
      { id: 'feb', type: 'float', caption: 'Feb' },
    ],
    data: [
      ['Mimesis', 1024.3, 'commercial', 2048.2, 4096.0],
      ['Mako', 2345.1, 'internal', 3465.3, { d: 12.5, color: 'selected' }],
      ['Edelweiss', 54.4, 'commercial', 564.8, 4652.3],
    ],
  },
  {
    id: 2,
    name: 'Employees list',
    header: [
      {
        id: 'employee_id',
        type: 'integer',
        caption: 'Employee ID',
      },
      {
        id: 'employee_name',
        type: 'string',
        caption: 'Employee Name',
        align: 'left',
      },
      {
        id: 'is_active',
        type: 'boolean',
        caption: 'Is Active',
      },
    ],
    data: [
      [101, 'John Doe', true],
      [102, 'Jane Smith', false],
      [103, 'Bob Johnson', { d: true, color: 'warning' }],
    ],
  },
  {
    id: 3,
    name: 'Products list',
    header: [
      {
        id: 'product_id',
        type: 'integer',
        caption: 'Product ID',
        align: 'right',
      },
      {
        id: 'product_name',
        type: 'string',
        caption: 'Product Name',
      },
      {
        id: 'is_in_stock',
        type: 'boolean',
        caption: 'In Stock',
      },
      {
        id: 'stock_count',
        type: 'integer',
        caption: 'Stock Count',
        align: 'right',
      },
    ],
    data: [
      [201, 'Widget A', true, 50],
      [202, 'Widget B', false, 0],
      [203, 'Widget C', { d: false, prop1: 'danger' }, 0],
    ],
  },
  {
    id: 4,
    name: 'Online orders',
    header: [
      { id: 'order_id', type: 'integer', caption: 'Order ID', align: 'right' },
      {
        id: 'product_name',
        type: 'string',
        caption: 'Product Name',
        align: 'left',
      },
      {
        id: 'is_shipped',
        type: 'boolean',
        caption: 'Shipped',
        align: 'center',
      },
      {
        id: 'order_date',
        type: 'date',
        caption: 'Order Date',
        align: 'center',
      },
    ],
    data: [
      [301, 'Gadget A', true, '2023-07-15'],
      [302, 'Gadget B', false, '2023-07-16'],
      [303, 'Gadget C', { d: true, prop1: 'delayed' }, '2023-07-17'],
    ],
  },
  {
    id: 5,
    name: 'Users list',
    header: [
      { id: 'id', type: 'integer', caption: 'ID', align: 'right' },
      { id: 'name', type: 'string', caption: 'Name', align: 'left' },
      { id: 'email', type: 'string', caption: 'Email' },
      {
        id: 'is_active',
        type: 'boolean',
        caption: 'Is Active',
      },
      {
        id: 'joined_date',
        type: 'date',
        caption: 'Joined Date',
        align: 'center',
      },
      {
        id: 'last_login',
        type: 'date',
        caption: 'Last Login',
        align: 'center',
      },
      { id: 'role', type: 'string', caption: 'Role', align: 'left' },
      { id: 'age', type: 'integer', caption: 'Age', align: 'right' },
      { id: 'country', type: 'string', caption: 'Country', align: 'left' },
      { id: 'city', type: 'string', caption: 'City', align: 'left' },
      { id: 'zip_code', type: 'integer', caption: 'Zip Code', align: 'right' },
      { id: 'salary', type: 'float', caption: 'Salary', align: 'right' },
      { id: 'rating', type: 'float', caption: 'Rating', align: 'right' },
      { id: 'reviews', type: 'integer', caption: 'Reviews', align: 'right' },
      { id: 'status', type: 'string', caption: 'Status', align: 'center' },
    ],
    data: [
      [
        1,
        'John Doe',
        'john.doe@example.com',
        true,
        '2022-01-01',
        '2023-07-01',
        'Manager',
        30,
        'USA',
        'New York',
        10001,
        50000.0,
        4.5,
        200,
        'Active',
      ],
      [
        2,
        'Jane Smith',
        'jane.smith@example.com',
        false,
        '2022-02-01',
        '2023-07-02',
        'Employee',
        25,
        'Canada',
        'Toronto',
        54321,
        30000.0,
        { d: 3, color: 'warning' },
        150,
        'Inactive',
      ],
      [
        3,
        'Bob Johnson',
        'bob.johnson@example.com',
        true,
        '2022-03-01',
        '2023-07-03',
        'Manager',
        35,
        'UK',
        'London',
        12345,
        60000.0,
        5.0,
        250,
        { d: 'On Leave', color: 'info' },
      ],
      [
        4,
        'Alice Davis',
        'alice.davis@example.com',
        false,
        '2022-04-01',
        '2023-07-04',
        'Employee',
        28,
        'Australia',
        'Sydney',
        98765,
        32000.0,
        4.2,
        180,
        'Inactive',
      ],
      [
        5,
        'Charlie Miller',
        'charlie.miller@example.com',
        true,
        '2022-05-01',
        '2023-07-05',
        'Manager',
        40,
        'USA',
        'Los Angeles',
        90001,
        55000.0,
        4.8,
        220,
        'Active',
      ],
      [
        6,
        'Eva Jackson',
        'eva.jackson@example.com',
        true,
        '2022-06-01',
        '2023-07-06',
        'Employee',
        26,
        'Canada',
        'Vancouver',
        65432,
        31000.0,
        { d: 3.5, color: 'warning' },
        160,
        'Active',
      ],
      [
        7,
        'George Clark',
        'george.clark@example.com',
        false,
        '2022-07-01',
        '2023-07-07',
        'Manager',
        38,
        'UK',
        'Birmingham',
        23456,
        58000.0,
        4.9,
        230,
        { d: 'On Leave', color: 'info' },
      ],
    ],
  },
];
